rvm: 1.9.3

script: "bundle exec rake spec"

before_script:
  - "cp config/database.yml{.template,}"
  - "cp spec/spec_helper{.travis,}.rb"
  - "cat config/database.yml"
  - "bundle exec rake db:setup --trace"